### ISSUE TITLE
Some elements marked as dirty during the forward method were not returned as output.

### ISSUE THREAD

**Issue by ayhokuyan** [MichaelFan01/STDC-Seg#16]
I have the following error message when trying to train. 
```python
Traceback (most recent call last):
  File "train.py", line 425, in <module>
    train()
  File "train.py", line 288, in train
    out, out16, out32, detail8 = net(im)
  File "/home/ayhan/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ayhan/env/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 799, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/ayhan/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ayhan/STDC-Seg/models/model_stages.py", line 272, in forward
    feat_res2, feat_res4, feat_res8, feat_res16, feat_cp8, feat_cp16 = self.cp(x)
  File "/home/ayhan/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ayhan/STDC-Seg/models/model_stages.py", line 141, in forward
    avg = self.conv_avg(avg)
  File "/home/ayhan/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ayhan/STDC-Seg/models/model_stages.py", line 31, in forward
    x = self.bn(x)
  File "/home/ayhan/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ayhan/STDC-Seg/modules/bn.py", line 118, in forward
    return inplace_abn_sync(x, self.weight, self.bias, self.running_mean, self.running_var,
RuntimeError: Some elements marked as dirty during the forward method were not returned as output. The inputs that are modified inplace must all be outputs of the Function.
```

I used the following code to run 
```
export CUDA_VISIBLE_DEVICES=0,1   
python -m torch.distributed.launch \
--nproc_per_node=2 train.py \
--respath checkpoints/train_STDC1-Seg/ \
--backbone STDCNet813 \
--mode train \
--n_workers_train 12 \
--n_workers_val 1 \
--max_iter 60000 \
--use_boundary_8 True  
```

I use Python 3.8.5 with PyTorch 1.9.1.
Would appreciate the help if anyone has been through the same.

**Comment by ayhokuyan** [comment]
In the README it mentions using python3.5.6, but it gives another error, related to python. I have used python 3.6 and all the other requirements the same, then it works.

**Comment by JunsukLee** [comment]
> README에서는 python3.5.6 사용에 대해 언급하지만 python과 관련된 또 다른 오류가 발생합니다. 나는 python 3.6과 다른 모든 요구 사항을 동일하게 사용했으며 작동합니다.

I also had the same problem.

How did you solve this problem?

Any help would be appreciated.
