### ISSUE TITLE
在训练时出现了TypeError: __init__() got an unexpected keyword argument 'find_unused_parameters‘

### ISSUE THREAD

**Issue by ding-Chen** [MichaelFan01/STDC-Seg#35]
我在单GPU环境下执行：
export CUDA_VISIBLE_DEVICES=0
python -m torch.distributed.launch \
--nproc_per_node=1 train.py \
--respath checkpoints/train_STDC1-Seg/ \
--backbone STDCNet813 \
--mode train \
--n_workers_train 12 \
--n_workers_val 1 \
--max_iter 60000 \
--use_boundary_8 True \
--pretrain_path checkpoints/STDCNet813M_73.91.tar 时

出现了以下错误：

Traceback (most recent call last):
  File "train.py", line 425, in <module>
    train()
  File "train.py", line 220, in train
    find_unused_parameters=True
TypeError: __init__() got an unexpected keyword argument 'find_unused_parameters’

请问大家有遇到过这个问题吗

**Comment by ydhongHIT** [comment]
我也遇到了这个问题，好像是融合不同stride的边界标签的问题，只使用单独stride的边界标签进行训练就没问题，不知道作者是什么处理的
