### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x87 in position 0: invalid start byte

### ISSUE THREAD

**Issue by GeneralJing** [MichaelFan01/STDC-Seg#75]
Traceback (most recent call last):
  File "train.py", line 4, in <module>
    from models.model_stages import BiSeNet
  File "/home/xxx/work/STDC-Seg/models/model_stages.py", line 12, in <module>
    from modules.bn import InPlaceABNSync as BatchNorm2d
  File "/home/xxxx/work/STDC-Seg/modules/__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "/home/xxxx/work/STDC-Seg/modules/bn.py", line 10, in <module>
    from .functions import *
  File "/home/xxxx/work/STDC-Seg/modules/functions.py", line 18, in <module>
    extra_cuda_cflags=["--expt-extended-lambda"])
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 680, in load
    is_python_module)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 845, in _jit_compile
    with_cuda=with_cuda
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/_cpp_extension_versioner.py", line 44, in bump_version_if_changed
    hash_value = hash_source_files(hash_value, source_files)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/_cpp_extension_versioner.py", line 17, in hash_source_files
    hash_value = update_hash(hash_value, file.read())
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x87 in position 0: invalid start byte

**Comment by guodong110** [comment]
您好，请问这个问题您解决了嘛
